networks:
    test:
        name: fabric_test
services:
    cli:
        command: /bin/bash
        container_name: cli
        environment:
            - GOPATH=/opt/gopath
            - FABRIC_LOGGING_SPEC=INFO
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        image: hyperledger/fabric-tools:2.5.4
        labels:
            service: hyperledger-fabric
        networks:
            - test
        stdin_open: "true"
        tty: "true"
        volumes:
            - /var/run/docker.sock:/host/var/run/docker.sock
            - ../organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    orderer.example.com:
        command: orderer
        container_name: orderer.example.com
        environment:
            - FABRIC_LOGGING_SPEC=INFO
            - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
            - ORDERER_GENERAL_LISTENPORT=7050
            - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
            - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
            - ORDERER_GENERAL_TLS_ENABLED=true
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
            - ORDERER_CHANNELPARTICIPATION_ENABLED=true
            - ORDERER_ADMIN_TLS_ENABLED=true
            - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
            - ORDERER_OPERATIONS_LISTENADDRESS=orderer.example.com:9443
            - ORDERER_METRICS_PROVIDER=prometheus
        image: hyperledger/fabric-orderer:2.5.4
        labels:
            service: hyperledger-fabric
        networks:
            - automobile
        ports:
            - 7050:7050
            - 7053:7053
            - 9443:9443
        volumes:
            - ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
            - ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
            - orderer.example.com:/var/hyperledger/production/orderer
        working_dir: /root
    org1peer0db:
        container_name: org1peer0db
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=adminpw
        image: couchdb:3.3.2
        labels:
            service: hyperledger-fabric
        networks:
            - automobile
        ports:
            - 7984:5984
    org1peer1db:
        container_name: org1peer1db
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=adminpw
        image: couchdb:3.3.2
        labels:
            service: hyperledger-fabric
        networks:
            - automobile
        ports:
            - 9984:5984
    org2peer0db:
        container_name: org2peer0db
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=adminpw
        image: couchdb:3.3.2
        labels:
            service: hyperledger-fabric
        networks:
            - automobile
        ports:
            - 11984:5984
    org2peer1db:
        container_name: org2peer1db
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=adminpw
        image: couchdb:3.3.2
        labels:
            service: hyperledger-fabric
        networks:
            - automobile
        ports:
            - 13984:5984
    org2peer2db:
        container_name: org2peer2db
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=adminpw
        image: couchdb:3.3.2
        labels:
            service: hyperledger-fabric
        networks:
            - automobile
        ports:
            - 15984:5984
    org3peer0db:
        container_name: org3peer0db
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=adminpw
        image: couchdb:3.3.2
        labels:
            service: hyperledger-fabric
        networks:
            - automobile
        ports:
            - 17984:5984
version: "3.7"
volumes:
    orderer.example.com: ""
