networks:
    test:
        name: fabric_test
services:
    ca_fe:
        command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
        container_name: ca_fe
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca-fe
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_PORT=8054
            - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:18054
        image: hyperledger/fabric-ca:1.5.7
        labels:
            service: hyperledger-fabric
        networks:
            - test
        ports:
            - 8054:8054
            - 18054:18054
        volumes:
            - ../organizations/fabric-ca/fe:/etc/hyperledger/fabric-ca-server
    ca_orderer:
        command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
        container_name: ca_orderer
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca-orderer
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_PORT=7054
            - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17054
        image: hyperledger/fabric-ca:1.5.7
        labels:
            service: hyperledger-fabric
        networks:
            - test
        ports:
            - 17054:17054
            - 17054:17054
        volumes:
            - ../organizations/fabric-ca/ordererOrg:/etc/hyperledger/fabric-ca-server
version: "3.7"
