networks:
    test:
        name: fabric_test
services:
    cli:
        command: /bin/bash
        container_name: cli
        depends_on:
            - peer0.fe.fh
        environment:
            - GOPATH=/opt/gopath
            - FABRIC_LOGGING_SPEC=INFO
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        image: hyperledger/fabric-tools:2.5.4
        labels:
            service: hyperledger-fabric
        networks:
            - test
        stdin_open: "true"
        tty: "true"
        volumes:
            - /var/run/docker.sock:/host/var/run/docker.sock
            - ../organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    fepeer0db:
        container_name: fepeer0db
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=adminpw
        image: couchdb:3.3.2
        labels:
            service: hyperledger-fabric
        networks:
            - test
        ports:
            - 5984:5984
    orderer.fh:
        command: orderer
        container_name: orderer.fh
        environment:
            - FABRIC_LOGGING_SPEC=INFO
            - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
            - ORDERER_GENERAL_LISTENPORT=7050
            - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
            - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
            - ORDERER_GENERAL_TLS_ENABLED=true
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
            - ORDERER_CHANNELPARTICIPATION_ENABLED=true
            - ORDERER_ADMIN_TLS_ENABLED=true
            - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
            - ORDERER_OPERATIONS_LISTENADDRESS=orderer.fh:9443
            - ORDERER_OPERATIONS_LISTENADDRESS=orderer.fh:9443
            - ORDERER_METRICS_PROVIDER=prometheus
        image: hyperledger/fabric-orderer:2.5.4
        labels:
            service: hyperledger-fabric
        networks:
            - test
        ports:
            - 7050:7050
            - 7053:7053
            - 9443:9443
        volumes:
            - ../organizations/ordererOrganizations/fh/orderers/orderer.fh/msp:/var/hyperledger/orderer/msp
            - ../organizations/ordererOrganizations/fh/orderers/orderer.fh/tls/:/var/hyperledger/orderer/tls
            - orderer.fh:/var/hyperledger/production/orderer
        working_dir: /root
    peer0.fe.fh:
        command: peer node start
        container_name: services:peer0.fe.fh
        depends_on:
            - fepeer0db
        environment:
            - FABRIC_LOGGING_SPEC=INFO
            - '#- FABRIC_LOGGING_SPEC=DEBUG'
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_PROFILE_ENABLED=false
            - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
            - '# Peer specific variables'
            - CORE_PEER_ID=peer0.fe.fh
            - CORE_PEER_ADDRESS=peer0.fe.fh:7051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
            - CORE_PEER_CHAINCODEADDRESS=peer0.fe.fh:7052
            - CORE_PEER_CHAINCODEADDRESS=peer0.fe.fh:7052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.fe.fh:7051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.fe.fh:7051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.fe.fh:7051
            - CORE_PEER_LOCALMSPID=FeMSP
            - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
            - CORE_OPERATIONS_LISTENADDRESS=peer0.fe.fh:9444
            - CORE_OPERATIONS_LISTENADDRESS=peer0.fe.fh:9444
            - CORE_METRICS_PROVIDER=prometheus
            - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={'peername':'peer0fe'}
            - CORE_CHAINCODE_EXECUTETIMEOUT=300s
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=fepeer0db:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=fepeer0db:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
        image: hyperledger/fabric-peer:2.5.4
        labels:
            service: hyperledger-fabric
        networks:
            - test
        ports:
            - 7051:7051
            - 9444:9444
            - 9444:9444
        volumes:
            - /var/run/docker.sock:/host/var/run/docker.sock
            - ../organizations/peerOrganizations/fe.fh/peers/peer0.fe.fh:/etc/hyperledger/fabric
            - peer0.fe.fh:/var/hyperledger/production
            - ../organizations/peerOrganizations/fe.fh/peers/peer0.fe.fh:/etc/hyperledger/fabric
            - peer0.fe.fh:/var/hyperledger/production
        working_dir: /root
version: "3.7"
volumes:
    orderer.fh: ""
    peer0.fe.fh: ""
