networks:
    test:
        name: fabric_test
services:
    ca_dealer:
        command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
        container_name: ca_dealer
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca-dealer
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_PORT=9054
            - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:19054
        image: hyperledger/fabric-ca:1.5.7
        labels:
            service: hyperledger-fabric
        networks:
            - test
        ports:
            - 9054:9054
            - 19054:19054
        volumes:
            - ../organizations/fabric-ca/dealer:/etc/hyperledger/fabric-ca-server
    ca_manufacturer:
        command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
        container_name: ca_manufacturer
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca-manufacturer
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_PORT=8054
            - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:18054
        image: hyperledger/fabric-ca:1.5.7
        labels:
            service: hyperledger-fabric
        networks:
            - test
        ports:
            - 8054:8054
            - 18054:18054
        volumes:
            - ../organizations/fabric-ca/manufacturer:/etc/hyperledger/fabric-ca-server
    ca_mvd:
        command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
        container_name: ca_mvd
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca-mvd
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_PORT=10054
            - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:20054
        image: hyperledger/fabric-ca:1.5.7
        labels:
            service: hyperledger-fabric
        networks:
            - test
        ports:
            - 10054:10054
            - 20054:20054
        volumes:
            - ../organizations/fabric-ca/mvd:/etc/hyperledger/fabric-ca-server
    ca_orderer:
        command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
        container_name: ca_orderer
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca-orderer
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_PORT=7054
            - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17054
        image: hyperledger/fabric-ca:1.5.7
        labels:
            service: hyperledger-fabric
        networks:
            - test
        ports:
            - 7054:7054
            - 17054:17054
        volumes:
            - ../organizations/fabric-ca/ordererOrg:/etc/hyperledger/fabric-ca-server
version: "3.7"
