networks:
    test:
        name: fabric_test
services:
    cli:
        command: /bin/bash
        container_name: cli
        depends_on:
            - peer0.manufacturer.auto.com
            - peer0.dealer.auto.com
            - peer0.mvd.auto.com
        environment:
            - GOPATH=/opt/gopath
            - FABRIC_LOGGING_SPEC=INFO
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        image: hyperledger/fabric-tools:2.5.4
        labels:
            service: hyperledger-fabric
        networks:
            - test
        stdin_open: true
        tty: true
        volumes:
            - /var/run/docker.sock:/host/var/run/docker.sock
            - ../organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    dealerpeer0db:
        container_name: dealerpeer0db
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=adminpw
        image: couchdb:3.3.2
        labels:
            service: hyperledger-fabric
        networks:
            - test
        ports:
            - 7984:5984
    manufacturerpeer0db:
        container_name: manufacturerpeer0db
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=adminpw
        image: couchdb:3.3.2
        labels:
            service: hyperledger-fabric
        networks:
            - test
        ports:
            - 5984:5984
    mvdpeer0db:
        container_name: mvdpeer0db
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=adminpw
        image: couchdb:3.3.2
        labels:
            service: hyperledger-fabric
        networks:
            - test
        ports:
            - 9984:5984
    orderer.auto.com:
        command: orderer
        container_name: orderer.auto.com
        environment:
            - FABRIC_LOGGING_SPEC=INFO
            - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
            - ORDERER_GENERAL_LISTENPORT=7050
            - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
            - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
            - ORDERER_GENERAL_TLS_ENABLED=true
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
            - ORDERER_CHANNELPARTICIPATION_ENABLED=true
            - ORDERER_ADMIN_TLS_ENABLED=true
            - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
            - ORDERER_OPERATIONS_LISTENADDRESS=orderer.auto.com:9443
            - ORDERER_METRICS_PROVIDER=prometheus
        image: hyperledger/fabric-orderer:2.5.4
        labels:
            service: hyperledger-fabric
        networks:
            - test
        ports:
            - 7050:7050
            - 7053:7053
            - 9443:9443
        volumes:
            - ../organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/msp:/var/hyperledger/orderer/msp
            - ../organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/tls/:/var/hyperledger/orderer/tls
            - orderer.auto.com:/var/hyperledger/production/orderer
        working_dir: /root
    peer0.dealer.auto.com:
        command: peer node start
        container_name: peer0.dealer.auto.com
        depends_on:
            - dealerpeer0db
        environment:
            - FABRIC_LOGGING_SPEC=INFO
            - '#- FABRIC_LOGGING_SPEC=DEBUG'
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_PROFILE_ENABLED=false
            - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
            - '# Peer specific variables'
            - CORE_PEER_ID=peer0.dealer.auto.com
            - CORE_PEER_ADDRESS=peer0.dealer.auto.com:9051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
            - CORE_PEER_CHAINCODEADDRESS=peer0.dealer.auto.com:9052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.dealer.auto.com:9051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.dealer.auto.com:9051
            - CORE_PEER_LOCALMSPID=DealerMSP
            - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
            - CORE_OPERATIONS_LISTENADDRESS=peer0.dealer.auto.com:9445
            - CORE_METRICS_PROVIDER=prometheus
            - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={'peername':'peer0dealer'}
            - CORE_CHAINCODE_EXECUTETIMEOUT=300s
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=dealerpeer0db:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
        image: hyperledger/fabric-peer:2.5.4
        labels:
            service: hyperledger-fabric
        networks:
            - test
        ports:
            - 9051:9051
            - 9445:9445
        volumes:
            - /var/run/docker.sock:/host/var/run/docker.sock
            - ../organizations/peerOrganizations/dealer.auto.com/peers/peer0.dealer.auto.com:/etc/hyperledger/fabric
            - peer0.dealer.auto.com:/var/hyperledger/production
        working_dir: /root
    peer0.manufacturer.auto.com:
        command: peer node start
        container_name: peer0.manufacturer.auto.com
        depends_on:
            - manufacturerpeer0db
        environment:
            - FABRIC_LOGGING_SPEC=INFO
            - '#- FABRIC_LOGGING_SPEC=DEBUG'
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_PROFILE_ENABLED=false
            - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
            - '# Peer specific variables'
            - CORE_PEER_ID=peer0.manufacturer.auto.com
            - CORE_PEER_ADDRESS=peer0.manufacturer.auto.com:7051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
            - CORE_PEER_CHAINCODEADDRESS=peer0.manufacturer.auto.com:7052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.manufacturer.auto.com:7051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.manufacturer.auto.com:7051
            - CORE_PEER_LOCALMSPID=ManufacturerMSP
            - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
            - CORE_OPERATIONS_LISTENADDRESS=peer0.manufacturer.auto.com:9444
            - CORE_METRICS_PROVIDER=prometheus
            - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={'peername':'peer0manufacturer'}
            - CORE_CHAINCODE_EXECUTETIMEOUT=300s
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=manufacturerpeer0db:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
        image: hyperledger/fabric-peer:2.5.4
        labels:
            service: hyperledger-fabric
        networks:
            - test
        ports:
            - 7051:7051
            - 9444:9444
        volumes:
            - /var/run/docker.sock:/host/var/run/docker.sock
            - ../organizations/peerOrganizations/manufacturer.auto.com/peers/peer0.manufacturer.auto.com:/etc/hyperledger/fabric
            - peer0.manufacturer.auto.com:/var/hyperledger/production
        working_dir: /root
    peer0.mvd.auto.com:
        command: peer node start
        container_name: peer0.mvd.auto.com
        depends_on:
            - mvdpeer0db
        environment:
            - FABRIC_LOGGING_SPEC=INFO
            - '#- FABRIC_LOGGING_SPEC=DEBUG'
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_PROFILE_ENABLED=false
            - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
            - '# Peer specific variables'
            - CORE_PEER_ID=peer0.mvd.auto.com
            - CORE_PEER_ADDRESS=peer0.mvd.auto.com:11051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
            - CORE_PEER_CHAINCODEADDRESS=peer0.mvd.auto.com:11052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.mvd.auto.com:11051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.mvd.auto.com:11051
            - CORE_PEER_LOCALMSPID=MvdMSP
            - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
            - CORE_OPERATIONS_LISTENADDRESS=peer0.mvd.auto.com:9446
            - CORE_METRICS_PROVIDER=prometheus
            - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={'peername':'peer0mvd'}
            - CORE_CHAINCODE_EXECUTETIMEOUT=300s
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=mvdpeer0db:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
        image: hyperledger/fabric-peer:2.5.4
        labels:
            service: hyperledger-fabric
        networks:
            - test
        ports:
            - 11051:11051
            - 9446:9446
        volumes:
            - /var/run/docker.sock:/host/var/run/docker.sock
            - ../organizations/peerOrganizations/mvd.auto.com/peers/peer0.mvd.auto.com:/etc/hyperledger/fabric
            - peer0.mvd.auto.com:/var/hyperledger/production
        working_dir: /root
version: "3.7"
volumes:
    orderer.auto.com: {}
    peer0.dealer.auto.com: {}
    peer0.manufacturer.auto.com: {}
    peer0.mvd.auto.com: {}
