application:
    Organizations: {}
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: ANY Readers
        Writers:
            Type: ImplicitMeta
            Rule: ANY Writers
        Admins:
            Type: ImplicitMeta
            Rule: MAJORITY Admins
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: MAJORITY Endorsement
        Endorsement:
            Type: ImplicitMeta
            Rule: MAJORITY Endorsement
    Capabilities:
        <<:
            V2_5: true
capabilities:
    application:
        V2_5: true
    channel:
        V2_0: true
    orderer:
        V2_0: true
channel:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: ANY Readers
        Writers:
            Type: ImplicitMeta
            Rule: ANY Writers
        Admins:
            Type: ImplicitMeta
            Rule: MAJORITY Admins
        BlockValidation:
            Type: ImplicitMeta
            Rule: ANY Writers
    Capabilities:
        <<:
            V2_0: true
orderer:
    Addresses:
        - orderer.auto.com:7050
    BatchTimeout: 2s
    BatchSize:
        maxmessagecount: 10
        absolutemaxbytes: 99 MB
        preferredmaxbytes: 512 KB
    Organizations: {}
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: ANY Readers
        Writers:
            Type: ImplicitMeta
            Rule: ANY Writers
        Admins:
            Type: ImplicitMeta
            Rule: MAJORITY Admins
        BlockValidation:
            Type: ImplicitMeta
            Rule: ANY Writers
organizations:
    - Name: OrdererOrg
      ID: OrdererMSP
      MSPDir: ../organizations/ordererOrganizations/auto.com/msp
      Policies:
        Readers:
            Type: Signature
            Rule: OR('OrdererMSP.member')
        Writers:
            Type: Signature
            Rule: OR('OrdererMSP.member')
        Admins:
            Type: Signature
            Rule: OR('OrdererMSP.member')
      OrdererEndpoints:
        - orderer.auto.com:7050
    - Name: ManufacturerMSP
      ID: ManufacturerMSP
      MSPDir: ../organizations/peerOrganizations/manufacturer.auto.com/msp
      Policies:
        Readers:
            Type: Signature
            Rule: OR('ManufacturerMSP.admin', 'ManufacturerMSP.peer', 'ManufacturerMSP.client')
        Writers:
            Type: Signature
            Rule: OR('ManufacturerMSP.admin','ManufacturerMSP.client')
        Admins:
            Type: Signature
            Rule: OR('ManufacturerMSP.admin')
        Endorsement:
            Type: Signature
            Rule: OR('ManufacturerMSP.peer')
    - Name: DealerMSP
      ID: DealerMSP
      MSPDir: ../organizations/peerOrganizations/dealer.auto.com/msp
      Policies:
        Readers:
            Type: Signature
            Rule: OR('DealerMSP.admin', 'DealerMSP.peer', 'DealerMSP.client')
        Writers:
            Type: Signature
            Rule: OR('DealerMSP.admin','DealerMSP.client')
        Admins:
            Type: Signature
            Rule: OR('DealerMSP.admin')
        Endorsement:
            Type: Signature
            Rule: OR('DealerMSP.peer')
    - Name: MvdMSP
      ID: MvdMSP
      MSPDir: ../organizations/peerOrganizations/mvd.auto.com/msp
      Policies:
        Readers:
            Type: Signature
            Rule: OR('MvdMSP.admin', 'MvdMSP.peer', 'MvdMSP.client')
        Writers:
            Type: Signature
            Rule: OR('MvdMSP.admin','MvdMSP.client')
        Admins:
            Type: Signature
            Rule: OR('MvdMSP.admin')
        Endorsement:
            Type: Signature
            Rule: OR('MvdMSP.peer')
profiles:
    ThreeOrgsChannel:
        <<:
            Policies:
                Readers:
                    Type: ImplicitMeta
                    Rule: ANY Readers
                Writers:
                    Type: ImplicitMeta
                    Rule: ANY Writers
                Admins:
                    Type: ImplicitMeta
                    Rule: MAJORITY Admins
                BlockValidation:
                    Type: ImplicitMeta
                    Rule: ANY Writers
            Capabilities:
                <<:
                    V2_0: true
        Application:
            <<:
                Organizations: {}
                Policies:
                    Readers:
                        Type: ImplicitMeta
                        Rule: ANY Readers
                    Writers:
                        Type: ImplicitMeta
                        Rule: ANY Writers
                    Admins:
                        Type: ImplicitMeta
                        Rule: MAJORITY Admins
                    LifecycleEndorsement:
                        Type: ImplicitMeta
                        Rule: MAJORITY Endorsement
                    Endorsement:
                        Type: ImplicitMeta
                        Rule: MAJORITY Endorsement
                Capabilities:
                    <<:
                        V2_5: true
            Capabilities:
                V2_5: true
            Organizations:
                - Name: ManufacturerMSP
                  ID: ManufacturerMSP
                  MSPDir: ../organizations/peerOrganizations/manufacturer.auto.com/msp
                  Policies:
                    Readers:
                        Type: Signature
                        Rule: OR('ManufacturerMSP.admin', 'ManufacturerMSP.peer', 'ManufacturerMSP.client')
                    Writers:
                        Type: Signature
                        Rule: OR('ManufacturerMSP.admin','ManufacturerMSP.client')
                    Admins:
                        Type: Signature
                        Rule: OR('ManufacturerMSP.admin')
                    Endorsement:
                        Type: Signature
                        Rule: OR('ManufacturerMSP.peer')
                - Name: DealerMSP
                  ID: DealerMSP
                  MSPDir: ../organizations/peerOrganizations/dealer.auto.com/msp
                  Policies:
                    Readers:
                        Type: Signature
                        Rule: OR('DealerMSP.admin', 'DealerMSP.peer', 'DealerMSP.client')
                    Writers:
                        Type: Signature
                        Rule: OR('DealerMSP.admin','DealerMSP.client')
                    Admins:
                        Type: Signature
                        Rule: OR('DealerMSP.admin')
                    Endorsement:
                        Type: Signature
                        Rule: OR('DealerMSP.peer')
                - Name: MvdMSP
                  ID: MvdMSP
                  MSPDir: ../organizations/peerOrganizations/mvd.auto.com/msp
                  Policies:
                    Readers:
                        Type: Signature
                        Rule: OR('MvdMSP.admin', 'MvdMSP.peer', 'MvdMSP.client')
                    Writers:
                        Type: Signature
                        Rule: OR('MvdMSP.admin','MvdMSP.client')
                    Admins:
                        Type: Signature
                        Rule: OR('MvdMSP.admin')
                    Endorsement:
                        Type: Signature
                        Rule: OR('MvdMSP.peer')
        orderer:
            <<:
                Addresses:
                    - orderer.auto.com:7050
                BatchTimeout: 2s
                BatchSize:
                    maxmessagecount: 10
                    absolutemaxbytes: 99 MB
                    preferredmaxbytes: 512 KB
                Organizations: {}
                Policies:
                    Readers:
                        Type: ImplicitMeta
                        Rule: ANY Readers
                    Writers:
                        Type: ImplicitMeta
                        Rule: ANY Writers
                    Admins:
                        Type: ImplicitMeta
                        Rule: MAJORITY Admins
                    BlockValidation:
                        Type: ImplicitMeta
                        Rule: ANY Writers
            Capabilities:
                V2_0: true
            EtcdRaft:
                Consenters:
                    - Host: orderer.auto.com
                      Port: "7050"
                      ClientTLSCert: ../organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/tls/server.crt
                      ServerTLSCert: ../organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/tls/server.crt
            OrdererType: etcdraft
            Organizations:
                Name: OrdererOrg
                ID: OrdererMSP
                MSPDir: ../organizations/ordererOrganizations/auto.com/msp
                Policies:
                    Readers:
                        Type: Signature
                        Rule: OR('OrdererMSP.member')
                    Writers:
                        Type: Signature
                        Rule: OR('OrdererMSP.member')
                    Admins:
                        Type: Signature
                        Rule: OR('OrdererMSP.member')
                OrdererEndpoints:
                    - orderer.auto.com:7050
